# Generated by Django 5.1 on 2024-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videflix', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=80),
        ),
    ]
