# Generated by Django 5.1 on 2024-09-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videflix', '0005_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
