# Generated by Django 5.1 on 2024-10-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videflix', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
